louvre_core:
    resource: "@LouvreCoreBundle/Resources/config/routing.yml"
    prefix:   /

louvre_resa:
    resource: "@LouvreResaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
